### ISSUE TITLE
Upgraded this wrapper to the new Tox API.

### ISSUE THREAD

**Issue by codedust** [organ/golibtox#10]
I upgraded this wrapper to the new Tox API.

Since @organ was not very active in the last months (his last contribution was on Sep 3, 2014), I decided to maintain this wrapper under [codedust/go-tox](https://github.com/codedust/go-tox).

Enjoy. ;)

**Comment by irth** [comment]
That's great to hear! I was waiting for someone to take over (I don't know go/c/tox enough to do this on my own).

**Comment by organ** [comment]
:+1:
